const _3Dmath = {
    'getP': function(a,b) { return (a+b)*2 },
    'getS': function(a,b) { return a*b },
    'getV': function(a,b,c) { return a*b*c },
    'P': {
        'plusA': function(a,b,p) { return ((a+p)+b)*2 },
        'plusB': function(a,b,p) { return (a+(b+p))*2 },
        'plusAB': function(a,b,p1,p2) { return ((a+p1)+(b+p2))*2 },
        'minusA': function(a,b,m) { return ((a-m)+b)*2 },
        'minusB': function(a,b,m) { return (a+(b-m))*2 },
        'minusAB': function(a,b,m1,m2) { return ((a-m1)+(b-m2))*2 },
    },
    'S': {
        'plusA': function(a,b,p) { return (a+p)*b },
        'plusB': function(a,b,p) { return a*(b+p) },
        'plusAB': function(a,b,p1,p2) { return (a+p1)*(b+p2) },
        'minusA': function(a,b,m) { return (a-m)*b },
        'minusB': function(a,b,m) { return a*(b-m) },
        'minusAB': function(a,b,m1,m2) { return (a-m1)*(b-m2) },
    },
    'V': {
        'plusA': function(a,b,c,p) { return (a+p)*b*c },
        'plusB': function(a,b,c,p) { return a*(b+p)*c },
        'plusC': function(a,b,c,p) { return a*b*(c+p) },
        'plusAB': function(a,b,c,p1,p2) { return (a+p1)*(b+p2)*c },
        'plusAC': function(a,b,c,p1,p2) { return (a+p1)*b*(c+p2) },
        'plusBC': function(a,b,c,p1,p2) { return a*(b+p1)*(c+p2) },
        'plusABC': function(a,b,c,p1,p2,p3) { return (a+p1)*(b+p2)*(c+p3) },
        'minusA': function(a,b,c,m) { return (a-m)*b*c },
        'minusB': function(a,b,c,m) { return a*(b-m)*c },
        'minusC': function(a,b,c,m) { return a*b*(c-m) },
        'minusAB': function(a,b,c,m1,m2) { return (a-m1)*(b-m2)*c },
        'minusAC': function(a,b,c,m1,m2) { return (a-m1)*b*(c-m2) },
        'minusBC': function(a,b,c,m1,m2) { return a*(b-m1)*(c-m2) },
        'minusABC': function(a,b,c,m1,m2,m3) { return (a-m1)*(b-m2)*(c-m3) },
    },
    'XYZ': {},
    'create3dIn2d': {},
}

export { _3Dmath }